### ISSUE TITLE
IE 11 signing not working. Promise is undefined

### ISSUE THREAD

**Issue by smartman** [hwcrypto/hwcrypto.js#23]
Latest hwcrypto.js 0.0.10 does not allow signing in IE 11 in Windows 10.

Error that is shown is: 'Promise' is undefined
![win10 ie](https://cloud.githubusercontent.com/assets/1007410/17526178/d9c34824-5e6e-11e6-9d2f-f75de7e8f981.PNG)

Internet Explorer exact version
![win10 ie ver](https://cloud.githubusercontent.com/assets/1007410/17526174/d68a8e9c-5e6e-11e6-91c6-f406d803bfed.PNG)

**Comment by martinpaljak** [comment]
You need to include a Promise polyfill, as available in hwcrypto-legacy.js or some other implementation like https://github.com/stefanpenner/es6-promise. This has been documented better in README.
