### ISSUE TITLE
hwcrypto.js + sk app + lithuanian drivers

### ISSUE THREAD

**Issue by tynisr** [hwcrypto/hwcrypto.js#28]
So right now we‘re struggling with the following hwcrypto.js + SK ID software issues:
•         When signing documents (hashes), the user is being asked for PIN only once. While browser stays opened, even after reloading pages, etc. – tested on Chrome 53.0.2785.116 m, Firefox 45.3.0. Tested with Lithuanian ID card, which uses CryptoCard software as a driver.
•         Sometimes certificate selection popup shows same certificate listed twice.
•         Sometimes certificate selection popup can’t detect certificate, but after a few tries – the certificate appears.
•         Using IE11 + usb key, issued by “Center of Registry”, the hwcrypto throws an error “invalid_argument”.

For us, the most critical one is that user is not being asked for PIN after entering it once. I wonder if there was testing and implemented use cases regarding SK software + Lithuanian ID cards.

**Comment by arminas** [comment]
It turns out that if there is a number of drivers installed in computer, then user sees multiple certificates listed in selection box.

And regarding PIN cache - still not clear where to start debugging. Maybe it's somehow related to that in Lithuania we use single PIN that is used for accessing both certificates - authentication and signing one.

**Comment by martinpaljak** [comment]
I think it is important to draw a line between the JS interface and on-host components. Right now there is a lot of mixup between these two, for historical reasons.

All of the described issues are with the native components, not the JS library. And thus should be directed there.

**Comment by martinpaljak** [comment]
moved to open-eid/chrome-token-signing#26
