### ISSUE TITLE
RSA signature support

### ISSUE THREAD

**Issue by wzoet** [hwcrypto/hwcrypto.js#32]
Is there any chance of RSA signature support or is this not implemented in the lower API? I was looking for a way to get a RSA-SHA256 signature of some data.

**Comment by martinpaljak** [comment]
RSA-SHA256 *is* what you get when you pass in a SHA-256 hash and the card in use does RSA (the only method currently supported)

**Comment by wzoet** [comment]
Alright, thank you, my mistake. I thought I was receiving not enough data regarding another implementation I was using in .net. It seems it was just the encoding fooling me.
