### ISSUE TITLE
get details of the Id card

### ISSUE THREAD

**Issue by wider2** [hwcrypto/hwcrypto.js#43]
is it possible with help of hwcrypto
to allow javascript get response from ID Card: name, username, email and so on ?

**Comment by mihkels** [comment]
You could use ASN.1 javascript lib to achieve this same result. Meaning you request ID-card public certificate and decode with ASN.1 decoder. 

ONe such lib is: https://github.com/indutny/asn1.js?utm_source=recordnotfound.com

**Comment by weilah** [comment]
Did you have any luck trying to get the ID Card details using hwcrypto?
