### ISSUE TITLE
getCertificate() failed: Error: no_certificates

### ISSUE THREAD

**Issue by Borisboky** [hwcrypto/hwcrypto.js#47]
I'm using MacOS High Sierra 10.13.3 and Chrome Version 65.0.3325.181 (Official Build) (64-bit), but I couldn't get it to work. 

I test it on [https://hwcrypto.github.io/demo/](https://hwcrypto.github.io/demo/) but when I try to sign in I get an error as follows:

```
Debug: hwcrypto.js 0.0.11 with Chrome native messaging extension 0.0.29/1.0.6.490
getCertificate() failed: Error: no_certificates
```

And in the console I get:

![screen shot 2018-03-26 at 11 49 43](https://user-images.githubusercontent.com/13819165/37899446-d40d6422-30eb-11e8-864c-1fa7644512e4.png)

I've installed `chome-token-signing `extension and _the content of the file in `/Library/Google/Chrome/NativeMessagingHosts/ee.ria.esteid.json` is as follows:

```
{
    "name": "ee.ria.esteid",
    "description": "Give signatures with your eID on the web",
    "path": "/Library/Google/Chrome/NativeMessagingHosts/chrome-token-signing.app/Contents/MacOS/chrome-token-signing",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://ckjefchnfjhjfedoccjbhjpbncimppeg/"
    ]
}

```

At first the path was (`/Library/Google/Chrome/NativeMessagingHosts/chrome-token-signing.app`), what is not correct and the error was `getCertificate() failed: Error: no_implementation` but I changed the path to `/Library/Google/Chrome/NativeMessagingHosts/chrome-token-signing.app/Contents/MacOS/chrome-token-signing` and the _implementation_ error is gone, but now I get _no_certificates_ error.

Any idea what is wrong?

**Comment by metsma** [comment]
Like I said previous ticket you need get your card ATR and install required middleware.
Then add ATR and middleware path to code
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L90-L163

**Comment by Borisboky** [comment]
Oke, and which lines do I need to change?

**Comment by metsma** [comment]
You need add something similar 
    static const std::string finPath("/Library/mPolluxDigiSign/libcryptoki.dylib");
and 
    {"3B7B940000806212515646696E454944", {finPath, "PIN1", "PIN2"}},

**Comment by Borisboky** [comment]
But what I do not understand is how can I use it then on the website? If I need to change the code of the extension then all users need to do it also. This cannot be so.


https://github.com/open-eid/chrome-token-signing/wiki/Token-Support

**Comment by metsma** [comment]
You can create pull request and next release will have necessary changes

**Comment by metsma** [comment]
https://github.com/open-eid/chrome-token-signing/pull/107
You can test this pull request
