### ISSUE TITLE
New estoniad id card

### ISSUE THREAD

**Issue by vadimkim** [hwcrypto/hwcrypto.js#54]
is new estonian id card supported?

**Comment by allanjuhanson** [comment]
I think it should be since the actual communication with smartcards is handled by browser extensions/plugins. So as long that the users browser extensions are up to date then there shouldn't be a problem.

**Comment by vadimkim** [comment]
Thank you for fast reply, Allan!
Just got the first result from new id-card + hwcrypto.js 0.0.13 : AUTH certificate got readed and signature is calculated. Our BE is just not ready for new SSN format.
