### ISSUE TITLE
GetCertificate performance

### ISSUE THREAD

**Issue by elion** [hwcrypto/hwcrypto.js#57]
GetCertificate takes too long.

The results on my i9 processor are the following:

|  filter |  min | max | unit | 
|---|---|---|---|
|  AUTH  | 12 | 15 | seconds  | 
|  SIGN | 10.6 | 11.6 | seconds  | 

Is the slow performance caused by browser plugin or could there be optimizations made in hwcrypto.js? 
The plugin I used is Chrome native messaging extension 0.0.30/1.0.9.507.

**Comment by metsma** [comment]
It depends from smartcard speed and smartcard middleware driver
