### ISSUE TITLE
RFE: Add support for signing UTF-8 text

### ISSUE THREAD

**Issue by minfrin** [hwcrypto/hwcrypto.js#58]
The Firefox web browser used to support a javascript function called crypto.signText() that presented some text to the end user, and invited the user to sign the text with a digital certificate.

This was removed from the Firefox project without a replacement.

I propose the same functionality be added to hwcrypto.js, so as to make it possible to sign text as was possible before.

Linked issues: https://github.com/open-eid/chrome-token-signing/issues/165

**Comment by martinpaljak** [comment]
Such implementation is not in the scope of this small interfacing/integration library, as explained in linked issue.
