### ISSUE TITLE
certificate base64/hex code doesn't contain the private key error

### ISSUE THREAD

**Issue by Mounika80244** [hwcrypto/hwcrypto.js#64]
I got the certificate from the token as a hex code ,so i need to use this certificate to sign a pdf in back end (.net C#). but I got error private key is missing. I have a doubt that always certificate from the token does not has private key or I made mistake  somewhere else .
Additional information: I got the details of the certificate from its hex code , but while signing only its showing No private key error
I am using hwcrypto.js for getting certificate from USB token.

**Comment by Mounika80244** [comment]
@metsma @martinpaljak @andris9 @ahoa if any body knows please help me

**Comment by martinpaljak** [comment]
Certificates don't contain private keys but public keys, by design. Use the `sign()` method to sign.

**Comment by Mounika80244** [comment]
_(Use the sign() method to sign.)_  I need to add signature to a pdf .here sign() method returns hex value of signature

**Comment by jchapelle** [comment]
Hey @Mounika80244,

Didi you succeed adding a signature to a pdf ?
I have the same use case ...
